--liquibase formatted sql

--changeSet Anatoly:1
CREATE TABLE sock(
    id         bigint generated by default as identity primary key,
    color      text,
    cotton_part int,
    quantity   int);

INSERT INTO sock(color, cotton_part, quantity)
VALUES ('black', 30, 100);
INSERT INTO sock(color, cotton_part, quantity)
VALUES ('red', 55, 150);
INSERT INTO sock(color, cotton_part, quantity)
VALUES ('yellow', 88, 222);